# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "chef/centos-6.5"
  config.vm.provision "shell", inline: "cp /vagrant/bamboo /etc/init.d/bamboo"
  config.vm.provision "shell", path: "general.sh"
  config.vm.provision "shell", path: "bamboo.sh"
  config.vm.network "private_network", type: "dhcp"
  config.vm.network :forwarded_port, host: 8085, guest: 8085
  config.vm.provider "virtualbox" do |v|
    v.name = "bamboo"
    v.memory = 1024
  end
end
