# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "chef/centos-6.5"
  config.vm.provision "shell", path: "docker.sh"
  config.vm.network :forwarded_port, host: 9000, guest: 9000
  config.vm.provider "virtualbox" do |v|
    v.name = "docker"
    v.memory = 1024
  end
end
