# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provision "shell", path: "docker.sh"
  config.vm.provider "virtualbox" do |v|
    v.name = "docker"
    v.memory = 1024
  end
end
