# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "chef/centos-6.5"
  config.vm.provision "shell", path: "general.sh"
  config.vm.synced_folder "../", "/vagrant/sync"
  config.vm.network :forwarded_port, host: 4567, guest: 8085
  config.vm.network :forwarded_port, host: 4568, guest: 7990
  config.vm.provider "virtualbox" do |v|
    v.name = "blank"
    v.memory = 2048
  end
end
