# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "chef/centos-6.5"
  config.vm.provision "shell", path: "general.sh"
  config.vm.provision "shell", path: "logstash.sh"
  # ElasticSearch
  config.vm.network :forwarded_port, host: 9200, guest: 9200
  # Kibana
  config.vm.network :forwarded_port, host: 8080, guest: 8080
  # Nagios
  config.vm.network :forwarded_port, host: 80, guest: 80
  # NSCA
  config.vm.network :forwarded_port, host: 5667, guest: 5667
  config.vm.provider "virtualbox" do |v|
    v.name = "logstash"
    v.memory = 1024
  end
end
