# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "chef/centos-6.5"
  config.vm.provision "shell", inline: "cp /vagrant/stash /etc/init.d/stash"
  config.vm.provision "shell", path: "general.sh"
  config.vm.provision "shell", path: "stash.sh"
  config.vm.network :forwarded_port, host: 7990, guest: 7990
  config.vm.provider "virtualbox" do |v|
    v.name = "stash"
    v.memory = 1024
  end
end
